* KongUp

** Introduction

KongUp is a dockerized service that runs on each host machine in a
Rancher/Cattle environment and automatically adds APIs to Kong as
services are deployed. KongUp listens to the docker events and
inspects a container's labels to add it to Kong.

** How Does it work?

KongUp binds to the docker socket on each host VM and listens for
"start" events. It them inspects the container that just started and
examines its labels. If GATEWAY\_VISIBLE is True, and GATEWAY\_URI is
provided, and if the container's environment matches with KongUp's
environment, KongUp will add it as an API to the Kong gateway
specified via environment variables. KongUp runs a port scan on the
API container to automatically find the port where the application is
running on.  Furthermore, KongUp sends notifications via HipChat.

#+BEGIN_SRC plantuml :file overview.png :results output

[*] -->  ExampleAPI
ExampleAPI --> DockerEngine : Deploys
ExampleAPI : ENVIRONMENT=DEV
ExampleAPI : GATEWAY_URI=/HELLO
ExampleAPI : GATEWAY_VISIBLE=True
DockerEngine --> KongUp : Start Event
KongUp : KONG_UP_KONG_ENVIRONMENT=DEV
KongUp : KONG_UP_KONG_HOST=kong.kong_rancher_stack
KongUp : KONG_UP_HIPCHAT_URL="abc.com/example_url"
KongUp : KONG_UP_LOG_LEVEL="DEBUG"
KongUp --> Kong : Add API
KongUp --> HipChat : Notification

#+END_SRC

** Labels 

The following labels must be set on services (containers) that you
want KongUp to process and add to Kong.

| Label           | Description                                                                                                                                                                                                                                                                         | Required |
| GATEWAY\_VISIBLE | Either True or False, Will Only add to API if set to True.                                                                                                                                                                                                                          | Yes      |
| GATEWA\Y_URI    | Kong uri (kong version >= 0.10.0) property                                                                                                                                                                                                                                          | Yes      |
| ENVIRONMENT     | The environment of the gateway to which the API should be added                                                                                                                                                                                                                     | Yes      |
| STRIP\_URI      | When matching an API via one of the uris prefixes, strip that matching prefix from the upstream URI to be requested. Optional. Defaults to 'True'. Value must be one of 'True', 'False', or ''. Your services must have some docker labels on them in order for KongUp to detect it. | Yes      |


** Environment Variables 


| Variable                   | Description                                                      | Required |
| KONG\_UP\_KONG_ENVIRONMENT | Which environment is this kong for?                              | Yes      |
| KONG\_UP\_KONG_HOST        | Hostname of machine where Kong is installed                      | Yes      |
| KONG\_UP\_HIPCHAT_URL      | Hipchat link to post notifications to                            | No       |
| KONG\_UP\_LOG_LEVEL        | Level of logging. Must be one of DEBUG, INFO, WARN, ERROR, FATAL | Yes      |


** Running in Docker

``` docker run -d \ -v /run/docker.sock:/var/run/docker.sock \ -e
KONG_UP_KONG_ENVIRONMENT="DEV" \ -e
KONG_UP_KONG_HOST="dev.api.deluxe.com" \ -e
KONG_UP_HIPCHAT_URL="xxx.com"\ -e KONG_UP_LOG_LEVEL="DEBUG"\
kong_up_image_name ```


** Running in Rancher

You can run the KongUp container on rancher with the same configs as
running it locally. But be sure you select the "Always run one
instance of this container on every host" option.
** Quick troubleshooting

Check the logs to see if there are any exceptions. There are no
external dependencies, so everything should work as expected.

** How to contribute

If you notice a bug or would like to add improvements, please send a
pull request with your fix.

** Supported Versions 

KongUp was tested on the following environment

- Rancher == 1.6.2
- Kong == 0.11.0
- Docker == 1.12.6
- HipChat == V2 API

** License

Copyright 2017 Deluxe Corporation

Licensed under the Apache License, Version 2.0 (the "License"); you
may not use this file except in compliance with the License.  You may
obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied.  See the License for the specific language governing
permissions and limitations under the License.
